# Generated by Django 2.0.dev20170514183117 on 2017-06-21 21:30

from django.db import migrations, models
import noticias.models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destacada',
            name='noticia',
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['fecha']},
        ),
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, height_field='alto_imagen', null=True, upload_to=noticias.models.upload_location, width_field='ancho_imagen'),
        ),
        migrations.DeleteModel(
            name='Destacada',
        ),
    ]
