# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20170621_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria']},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, height_field='alto_imagen', null=True, upload_to='', width_field='ancho_imagen'),
        ),
    ]
